# Generated by Django 2.1 on 2019-03-07 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abcd', '0002_auto_20190307_0538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.SlugField(default='yashsharma', max_length=20),
        ),
    ]
