# Generated by Django 2.1 on 2019-03-07 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abcd', '0003_auto_20190307_0542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.SlugField(default='yashsharma', max_length=1),
        ),
    ]
