# Generated by Django 2.1 on 2019-03-07 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abcd', '0004_auto_20190307_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(default='yashsharma', max_length=50, verbose_name='password'),
        ),
    ]
