# Generated by Django 2.1 on 2019-03-07 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abcd', '0005_auto_20190307_0544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.TextField(),
        ),
    ]
